# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
      - dave@dav.ee
env:
  matrix:
    - ROS_DISTRO="indigo"  ROS_REPO=ros              
    - ROS_DISTRO="indigo"  ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="indigo"  UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ros-planning/moveit/indigo-devel/moveit.rosinstall
    - ROS_DISTRO="jade"  ROS_REPO=ros              UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/130s/moveit_robots/i/remove_j/dependency.rosinstall
    - ROS_DISTRO="jade"  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/130s/moveit_robots/i/remove_j/dependency.rosinstall
    - ROS_DISTRO="jade"  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/130s/moveit_robots/i/remove_j/dependency.rosinstall,https://raw.githubusercontent.com/ros-planning/moveit/jade-devel/moveit.rosinstall  # Test MoveIt! from source from devel repo.
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh